###############################################################################
# AURORA-172 FPGA Constraints File
# Target: Intel Agilex 7 (AGIB027F29E1V)
# Tool: Intel Quartus Prime Pro 24.1+
# 
# This file contains all timing, placement, and I/O constraints for
# FPGA prototyping on Intel Agilex platform.
###############################################################################

###############################################################################
# 1. CLOCK DEFINITIONS
###############################################################################

# Primary system clock (500 MHz from external oscillator)
create_clock -name sys_clk -period 2.000 [get_ports sys_clk_p]
create_clock -name sys_clk_n -period 2.000 [get_ports sys_clk_n]

# Derived clocks (generated by PLL)
create_generated_clock -name g_core_clk \
    -source [get_ports sys_clk_p] \
    -multiply_by 1 \
    [get_pins pll_0|altera_pll_i|outclk[0]]

create_generated_clock -name h_core_clk \
    -source [get_ports sys_clk_p] \
    -divide_by 2 \
    [get_pins pll_0|altera_pll_i|outclk[1]]

create_generated_clock -name ai_core_clk \
    -source [get_ports sys_clk_p] \
    -divide_by 4 \
    [get_pins pll_0|altera_pll_i|outclk[2]]

create_generated_clock -name mem_fabric_clk \
    -source [get_ports sys_clk_p] \
    -multiply_by 2 -divide_by 3 \
    [get_pins pll_0|altera_pll_i|outclk[3]]

create_generated_clock -name interconnect_clk \
    -source [get_ports sys_clk_p] \
    -divide_by 2 \
    [get_pins pll_0|altera_pll_i|outclk[4]]

create_generated_clock -name debug_clk \
    -source [get_ports sys_clk_p] \
    -divide_by 10 \
    [get_pins pll_0|altera_pll_i|outclk[5]]

###############################################################################
# 2. CLOCK UNCERTAAINTY
###############################################################################

set_clock_uncertainty -setup 0.100 [get_clocks sys_clk]
set_clock_uncertainty -hold 0.050 [get_clocks sys_clk]

set_clock_uncertainty -setup 0.080 [get_clocks g_core_clk]
set_clock_uncertainty -hold 0.040 [get_clocks g_core_clk]

set_clock_uncertainty -setup 0.100 [get_clocks h_core_clk]
set_clock_uncertainty -hold 0.050 [get_clocks h_core_clk]

set_clock_uncertainty -setup 0.120 [get_clocks ai_core_clk]
set_clock_uncertainty -hold 0.060 [get_clocks ai_core_clk]

set_clock_uncertainty -setup 0.090 [get_clocks mem_fabric_clk]
set_clock_uncertainty -hold 0.045 [get_clocks mem_fabric_clk]

set_clock_uncertainty -setup 0.100 [get_clocks interconnect_clk]
set_clock_uncertainty -hold 0.050 [get_clocks interconnect_clk]

###############################################################################
# 3. CLOCK DOMAIN CROSSING (CDC)
###############################################################################

set_clock_groups -asynchronous \
    -group [get_clocks g_core_clk] \
    -group [get_clocks h_core_clk] \
    -group [get_clocks ai_core_clk] \
    -group [get_clocks mem_fabric_clk] \
    -group [get_clocks interconnect_clk]

# Synchronizer registers
set_instance_assignment -name SYNC_CHAIN_LENGTH 3 \
    -to *cdc_sync* -entity cdc_lib

###############################################################################
# 4. I/O CONSTRAINTS
###############################################################################

# DDR4/HBM interface
set_instance_assignment -name IO_STANDARD "1.2 V TT Differential" \
    -to {ddr4_dq[*] ddr4_dqs_p[*] ddr4_dqs_n[*]}

set_instance_assignment -name IO_STANDARD "1.2 V" \
    -to {ddr4_addr[*] ddr4_ba[*] ddr4_cke[*]}

# PCIe Gen5
set_instance_assignment -name IO_STANDARD "1.8 V" \
    -to {pcie_tx[*] pcie_rx[*]}

# Debug JTAG
set_instance_assignment -name IO_STANDARD "1.8 V" \
    -to {jtag_tck jtag_tms jtag_tdi jtag_tdo jtag_trst_n}

# UART
set_instance_assignment -name IO_STANDARD "1.8 V" \
    -to {uart_tx uart_rx}

# GPIO/LEDs
set_instance_assignment -name IO_STANDARD "1.8 V" \
    -to {led_status[*] gpio_int_n}

###############################################################################
# 5. TIMING EXCEPTIONS
###############################################################################

# G-Core critical paths
set_max_delay 1.800 \
    -from [get_cells -filter {NAME =~ *g_core*/*exec_pipe*}] \
    -to [get_cells -filter {NAME =~ *g_core*/*exec_pipe*}]

# AI Branch predictor
set_max_delay 1.900 \
    -from [get_cells -filter {NAME =~ *g_core*/*ai_bp*}] \
    -to [get_cells -filter {NAME =~ *g_core*/*fetch*}]

# Memory fabric
set_max_delay 2.000 \
    -from [get_cells -filter {NAME =~ *memory_fabric*/*arbiter*}] \
    -to [get_cells -filter {NAME =~ *memory_fabric*/*cache*}]

# Aurora Fabric
set_max_delay 2.000 \
    -from [get_cells -filter {NAME =~ *aurora_fabric*/*router*}] \
    -to [get_cells -filter {NAME =~ *aurora_fabric*/*input_fifo*}]

###############################################################################
# 6. MULTICYCLE PATHS
###############################################################################

# DMA engine
set_multicycle_path -setup 4 \
    -from [get_cells -filter {NAME =~ *dma_engine*/*ch[*]/control*}] \
    -to [get_cells -filter {NAME =~ *dma_engine*/*ch[*]/status*}]

set_multicycle_path -hold 3 \
    -from [get_cells -filter {NAME =~ *dma_engine*/*ch[*]/control*}] \
    -to [get_cells -filter {NAME =~ *dma_engine*/*ch[*]/status*}]

# Cache coherency
set_multicycle_path -setup 3 \
    -from [get_cells -filter {NAME =~ *cache_coherency*/*directory*}] \
    -to [get_cells -filter {NAME =~ *cache_coherency*/*snoop*}]

set_multicycle_path -hold 2 \
    -from [get_cells -filter {NAME =~ *cache_coherency*/*directory*}] \
    -to [get_cells -filter {NAME =~ *cache_coherency*/*snoop*}]

# Power management
set_multicycle_path -setup 10 \
    -from [get_cells -filter {NAME =~ *power_mgmt*/*fsm*}] \
    -to [get_cells -filter {NAME =~ *power_mgmt*/*control*}]

set_multicycle_path -hold 9 \
    -from [get_cells -filter {NAME =~ *power_mgmt*/*fsm*}] \
    -to [get_cells -filter {NAME =~ *power_mgmt*/*control*}]

# NPU
set_multicycle_path -setup 8 \
    -from [get_cells -filter {NAME =~ *npu_cluster*/*pe[*]/weight_buf*}] \
    -to [get_cells -filter {NAME =~ *npu_cluster*/*pe[*]/mac*}]

set_multicycle_path -hold 7 \
    -from [get_cells -filter {NAME =~ *npu_cluster*/*pe[*]/weight_buf*}] \
    -to [get_cells -filter {NAME =~ *npu_cluster*/*pe[*]/mac*}]

###############################################################################
# 7. FALSE PATHS
###############################################################################

set_false_path -from [get_ports rst_n]
set_false_path -to [get_ports rst_n]

set_false_path -from [get_cells -filter {NAME =~ *debug_ctrl*}]
set_false_path -to [get_cells -filter {NAME =~ *debug_ctrl*}]

set_false_path -from [get_ports test_mode_en]
set_false_path -to [get_cells -filter {NAME =~ *test_mode*}]

###############################################################################
# 8. PHYSICAL CONSTRAINTS - Logic Lock Regions
###############################################################################

# G-Core region (SLR 0 equivalent)
set_instance_assignment -name LOGIC_LOCK_REGION G_CORE_REGION \
    -to *g_core*

create_logic_lock_region -name G_CORE_REGION \
    -origin X0_Y0 -snap_to_grid 1000 \
    -right 80000 -top 200000

# H-Core region (SLR 1)
set_instance_assignment -name LOGIC_LOCK_REGION H_CORE_REGION \
    -to *h_core*

create_logic_lock_region -name H_CORE_REGION \
    -origin X80000_Y0 -snap_to_grid 1000 \
    -right 160000 -top 200000

# AI-Core + NPU region (SLR 2)
set_instance_assignment -name LOGIC_LOCK_REGION AI_CORE_REGION \
    -to *a_core* *npu_cluster*

create_logic_lock_region -name AI_CORE_REGION \
    -origin X0_Y200000 -snap_to_grid 1000 \
    -right 160000 -top 400000

# Memory Fabric (center)
set_instance_assignment -name LOGIC_LOCK_REGION MEM_FABRIC_REGION \
    -to *memory_fabric*

create_logic_lock_region -name MEM_FABRIC_REGION \
    -origin X80000_Y200000 -snap_to_grid 1000 \
    -right 160000 -top 300000

###############################################################################
# 9. DSP & BRAM CONSTRAINTS
###############################################################################

# Target DSP utilization <85%
# (Quartus automatically optimizes, but we can set hints)

set_global_assignment -name OPTIMIZATION_MODE "Aggressive Performance"
set_global_assignment -name PHYSICAL_SYNTHESIS_EFFORT "Extra"

###############################################################################
# 10. POWER CONSTRAINTS
###############################################################################

set_operating_conditions -family "Agilex 7" -max 85.0 -min 0.0

###############################################################################
# END OF CONSTRAINTS
###############################################################################
