`ifndef AURORA_TIMING_CONSTANTS_SVH
`define AURORA_TIMING_CONSTANTS_SVH

// DDR4 timing parameters
`define DDR4_READ_LATENCY_CYCLES    16'd20
`define DDR4_WRITE_LATENCY_CYCLES   16'd12
`define DDR4_ACTIVATE_CYCLES        16'd4
`define DDR4_TIMEOUT_CYCLES         16'd1000

// UART
`define UART_HEARTBEAT_INTERVAL     16'd50000

`endif
